# Generated by Django 4.2.24 on 2025-09-26 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='code_melli',
        ),
    ]
