# Generated by Django 4.2.25 on 2026-08-07 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receptor', models.CharField(max_length=20, verbose_name='شماره گیرنده')),
                ('sender', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره ارسال کننده')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('send_type', models.CharField(choices=[('single', 'ارسال تکی'), ('ready_device', 'آماده تحویل'), ('bulk', 'ارسال گروهی')], default='single', max_length=30, verbose_name='نوع ارسال')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('success', 'موفق'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('message_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه پیام کاوه نگار')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to=settings.AUTH_USER_MODEL, verbose_name='ارسال توسط')),
            ],
            options={
                'verbose_name': 'گزارش پیامک',
                'verbose_name_plural': 'گزارش پیامک\u200cها',
                'ordering': ['-id'],
            },
        ),
    ]
