# Generated by Django 4.2.24 on 2025-09-27 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SMS',
            new_name='SMS_Number',
        ),
    ]
