# Generated by Django 4.2.24 on 2025-09-27 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_sms_sms_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SMS_Number',
            new_name='SMSNumber',
        ),
    ]
