# Generated by Django 4.2.24 on 2025-09-27 07:11

import app.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_sms_number_smsnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[app.accounts.validators.validate_iranian_cellphone_number])),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='smsnumber',
            options={'ordering': ['-id']},
        ),
    ]
