# Generated by Django 4.2.24 on 2025-09-27 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_phonenumber_alter_smsnumber_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumber',
            old_name='phone_number',
            new_name='tel',
        ),
    ]
