# Generated by Django 4.2.24 on 2025-09-26 16:04

import app.accounts.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پذیرش')),
                ('exit_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ خروج')),
                ('device_name', models.CharField(max_length=100, verbose_name='نام دستگاه')),
                ('device_type', models.CharField(choices=[('tv', 'تلویزیون'), ('monitor', 'مانیتور'), ('projector', 'پروژکتور'), ('other', 'سایر')], max_length=20, verbose_name='نوع دستگاه')),
                ('device_model', models.CharField(max_length=100, verbose_name='مدل دستگاه')),
                ('device_serial', models.CharField(max_length=100, unique=True, verbose_name='سریال دستگاه')),
                ('owner_name', models.CharField(max_length=100, verbose_name='نام مالک')),
                ('owner_phone', models.CharField(max_length=12, validators=[app.accounts.validators.validate_iranian_cellphone_number], verbose_name='شماره تلفن همراه')),
                ('owner_national_id', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('owner_landline', models.CharField(blank=True, max_length=15, null=True, verbose_name='تلفن ثابت')),
                ('owner_address', models.TextField(verbose_name='آدرس')),
                ('appearance_issue', models.TextField(blank=True, null=True, verbose_name='ایراد ظاهری')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('technician_note', models.TextField(blank=True, null=True, verbose_name='نظر تکنسین')),
                ('cost', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='هزینه')),
                ('has_warranty', models.BooleanField(default=False, verbose_name='آیا گارانتی دارد؟')),
                ('warranty_period', models.CharField(blank=True, max_length=50, null=True, verbose_name='مدت گارانتی')),
                ('is_ready', models.BooleanField(default=False, verbose_name='آیا آماده تحویل است؟')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptions', to=settings.AUTH_USER_MODEL, verbose_name='پذیرش توسط')),
            ],
        ),
    ]
