# Generated by Django 4.2.24 on 2025-09-27 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paziresh', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicereception',
            options={'ordering': ['-id']},
        ),
    ]
