# Generated by Django 4.2.25 on 2026-02-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paziresh', '0002_alter_devicereception_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicereception',
            name='delivery_type',
            field=models.CharField(choices=[('in_person', 'حضوری'), ('online', 'آنلاین')], default='in_person', max_length=20, verbose_name='نوع تحویل'),
        ),
        migrations.AddField(
            model_name='devicereception',
            name='reception_type',
            field=models.CharField(choices=[('in_person', 'حضوری'), ('online', 'آنلاین')], default='in_person', max_length=20, verbose_name='نوع پذیرش'),
        ),
    ]
