# Generated by Django 4.2.25 on 2026-07-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paziresh', '0003_devicereception_delivery_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicereception',
            name='delivery_type',
            field=models.CharField(choices=[('in_person', 'حضوری'), ('online', 'پیک رسان')], default='in_person', max_length=20, verbose_name='نوع تحویل'),
        ),
        migrations.AlterField(
            model_name='devicereception',
            name='reception_type',
            field=models.CharField(choices=[('in_person', 'حضوری'), ('online', 'پیک رسان')], default='in_person', max_length=20, verbose_name='نوع پذیرش'),
        ),
    ]
