# Generated by Django 4.2.25 on 2026-07-31 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paziresh', '0004_alter_devicereception_delivery_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات گارانتی')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع گارانتی')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان گارانتی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to='paziresh.devicereception', verbose_name='دستگاه مربوطه')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranties_issued', to=settings.AUTH_USER_MODEL, verbose_name='صادر شده توسط')),
            ],
            options={
                'verbose_name': 'گارانتی',
                'verbose_name_plural': 'گارانتی\u200cها',
                'ordering': ['-id'],
            },
        ),
    ]
