# Generated by Django 4.2.25 on 2026-08-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paziresh', '0005_warranty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicereception',
            name='is_ready',
        ),
        migrations.AddField(
            model_name='devicereception',
            name='status',
            field=models.CharField(choices=[('repairing', 'در حال تعمیر'), ('ready', 'آماده تحویل'), ('delivered', 'تحویل داده شده')], default='repairing', max_length=20, verbose_name='وضعیت'),
        ),
    ]
